### ISSUE TITLE
Very large increase in CPU consumption after migration from Keycloak 21.1.2 to 24.0.4

### ISSUE THREAD

**Issue by nowyp** [crossplane-contrib/provider-keycloak#108]
Hi,

we noticed very large CPU increase after switch from Keycloak 21.1.2 to 24.0.4. Initially we assumed that the problem was related that we use older provider version (v0.17.0) but we upgraded to the latest v0.22.0 and it did not help.

Below is Grafana CPU usage chart and how is changed when we upgraded Keycloak:

![image](https://github.com/crossplane-contrib/provider-keycloak/assets/95233685/0005afa4-fd9d-4208-8c37-29df0da8815b)

Except the Keycloak upgrade we did not have in this specific release any other changes. We also do not observe any errors or anything like that in our logs for keycloak provider.

**Comment by nowyp** [comment]
- ProtocolMapper
- Client
- Role

Chart with bandwidth:

![image](https://github.com/crossplane-contrib/provider-keycloak/assets/95233685/500fe1c1-20be-4637-ad4e-991974655117)

**Comment by Breee** [comment]
There is now also away to get prometheus metrics about resources: https://blog.crossplane.io/crossplane-v1-16/
I have to check out how to implement that, reference:  https://github.com/crossplane-contrib/provider-upjet-aws/pull/1281/files

**Comment by Breee** [comment]
> * ProtocolMapper
> * Client
> * Role
> 
> Chart with bandwidth:
> 
> ![image](https://private-user-images.githubusercontent.com/95233685/339781357-500fe1c1-20be-4637-ad4e-991974655117.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNzIwOTYsIm5iZiI6MTcxODM3MTc5NiwicGF0aCI6Ii85NTIzMzY4NS8zMzk3ODEzNTctNTAwZmUxYzEtMjBiZS00NjM3LWFkNGUtOTkxOTc0NjU1MTE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDEzMjk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkNzY5M2Q1NDg1NzBlYWEyNjJjODc3OWEzNmY4Mjg2YmZmYTc1NTU1Y2ZlMmIwYjRlNjkxYjlkYTQ2MTllYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pfYY0xAme-RWseL6U0ZJjYofq-KCfuYiyR9I6eBOULI)

So maybe it's really the protocol mappers: https://github.com/crossplane-contrib/provider-keycloak/issues/65#issuecomment-2047479756  i have to check that out as well -> you can try that workaround

**Comment by nowyp** [comment]
Ok - in our case it was just missing `introspection.token.claim: "true"` value which case terafform plan/apply loop with some default one in keycloak (so in order to make it correctly all expected values needs to be provided). We're verifiing solution right now.

**Comment by nowyp** [comment]
@Breee the change helps in our case decrese the CPU usage from ~ 7 cores to stable 2-3 cores but it seems that there is some memory leak (maybe in Terraform - I see there is v.1.4.6 version used) which cause that provider over time take more and more meory:

![image](https://github.com/crossplane-contrib/provider-keycloak/assets/95233685/fb17a580-d320-4887-8668-b7e4fd8541a5)

**Comment by Breee** [comment]
Can you test if the leaks go away with: 

```
xpkg.upbound.io/crossplane-contrib/provider-keycloak:v0.23.0
```

?

**Comment by vladimirblahoz** [comment]
I will have to re-test it multiple times with different memory limits, but in our case after first trials it seems it is still leaking even in v 0.23

**Comment by nowyp** [comment]
@Breee applied the change. Will let you know about the results.

**Comment by Breee** [comment]
Tracking that in #118   -> will try to fix that asap

**Comment by Breee** [comment]
please test out @nowyp @vladimirblahoz 

```
xpkg.upbound.io/crossplane-contrib/provider-keycloak:v0.24.0-rc.2
```

it contains changes of pr https://github.com/crossplane-contrib/provider-keycloak/pull/124

**Comment by nowyp** [comment]
@Breee thanks for update. Applied changes to our dev cluster - let you know later about the outcome

**Comment by nowyp** [comment]
First tests looks promising:

![keycloak-upgrade](https://github.com/crossplane-contrib/provider-keycloak/assets/95233685/2e9cd022-56bd-4b50-b641-80088eaa2612)

**Comment by vladimirblahoz** [comment]
Our long term results don't look so promising.
![image](https://github.com/crossplane-contrib/provider-keycloak/assets/104296051/566ba123-69ba-4255-ae5a-be0b1d058bf1)

Keycloak provider pod getting OOMKilled like every hour and a half overflowing its 512Mi memory limit very regularly (running on 0.24.0-rc.2).

Not sure if this can have something to do with broken built-in clients/roles resource constantly and unsuccessfully trying to sync...

**Comment by Breee** [comment]
> Our long term results don't look so promising. ![image](https://private-user-images.githubusercontent.com/104296051/344977826-566ba123-69ba-4255-ae5a-be0b1d058bf1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MTU1NTgsIm5iZiI6MTcxOTkxNTI1OCwicGF0aCI6Ii8xMDQyOTYwNTEvMzQ0OTc3ODI2LTU2NmJhMTIzLTY5YmEtNDI1NS1hZTVhLWJlMGIxZDA1OGJmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMlQxMDE0MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYmU3NjkxMjczNzE5YmZlYzJjOTdlMTJhN2NlYWNlOTE5NzQ5NzRiMzg1YjZiNGU1NGZiNGUxMDRlYzI3MDg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Cv41ajkWXxybaAb_GThoF7ulHnRGghn2lgNGfh-UKtw)
> 
> Keycloak provider pod getting OOMKilled like every hour and a half overflowing its 512Mi memory limit very regularly (running on 0.24.0-rc.2).
> 
> Not sure if this can have something to do with broken built-in clients/roles resource constantly and unsuccessfully trying to sync...

probably. i have to verify that myself

**Comment by nowyp** [comment]
In our side still stable:

![image](https://github.com/crossplane-contrib/provider-keycloak/assets/95233685/eb26fb6d-7030-4ff4-bc01-89ef3ad61075)

**Comment by Breee** [comment]
let's consolidate further discussions into #118
