### ISSUE TITLE
Huge memory requirements

### ISSUE THREAD

**Issue by vladimirblahoz** [crossplane-contrib/provider-keycloak#115]
Hi, guys!
We are experiencing quite significant spikes on the memory usage during the reconciliation process. We are rising the memory limits like every other week. Now our provider-keycloak pod is stuck in the OOMKilled caused Crash loop with `600Mi` of memory, so need to rise it up again.

What is the normal memory consumption? Is it expected that the provider eats up more memory during any deployment than keycloak itself? Or is that an indication that something is wrong with our crossplane resources?

**Comment by Breee** [comment]
That's related to #108  
I'll try to to update terraform and see if the issues go away

**Comment by Breee** [comment]
Can you test if the leaks go away with: 

```
xpkg.upbound.io/crossplane-contrib/provider-keycloak:v0.23.0
```

**Comment by Breee** [comment]
let's consolidate further discussions into https://github.com/crossplane-contrib/provider-keycloak/issues/118
