### ISSUE TITLE
How to assign a real role to a real user?

### ISSUE THREAD

**Issue by ckazimie** [crossplane-contrib/provider-keycloak#125]
I want to define a couple of user and assign them to realm roles. I cannot see a place to specify the roles in the User resource?
Could you provide an example?

**Comment by Breee** [comment]
Greetings,

You have to use the Roles object 

Check https://github.com/crossplane-contrib/provider-keycloak/blob/main/examples-generated/user/v1alpha1/roles.yaml

At a bigger scale, I'd recommend using groups over direct role assignments tho.

**Comment by ckazimie** [comment]
Thank you, @Breee It works! :)

**Comment by ckazimie** [comment]
Thank you, @Breee  It works! :)
