### ISSUE TITLE
Link Role to ClientScope: no clientScopeIdRef ??

### ISSUE THREAD

**Issue by twuyts** [crossplane-contrib/provider-keycloak#142]
I'm trying to add a role to a clientscope in keycloak.
This involves 3 manifests:
1. `openidclient.keycloak.crossplane.io/v1alpha1` `ClientScope`
2. `role.keycloak.crossplane.io/v1alpha1` `Role`
3. `client.keycloak.crossplane.io/v1alpha1`: `RoleMapper`

However, the last one poses a problem. The CRD only foresees a `clientScopeId` to refer to the clientscope. How can I pass the id of the clientscope created in step 1? The CRD only provides the `clientScopeId` field, which only works if you pass in the keycloak internal uuid of the clientscope. There is no `clientScopeIdRef` for this object.

I'm using xpkg.upbound.io/crossplane-contrib/provider-keycloak:v1.1.0

**Comment by Breee** [comment]
Good morning,  
Sorry for the radio silence.  I'll fix that asap

**Comment by Breee** [comment]
please test if  `xpkg.upbound.io/crossplane-contrib/provider-keycloak:v1.2.0` fixes that for you :)

**Comment by twuyts** [comment]
works like a charm.
Thx for the quick fix!
