### ISSUE TITLE
groups.user.keycloak.crossplane.io doesn't resolve groupIdsRefs or groupIdsSelector

### ISSUE THREAD

**Issue by j2L4e** [crossplane-contrib/provider-keycloak#164]
While the groupIdsRefs property is generated for the groups.user.keycloak.crossplane.io CRD, it doesn't have any effect at runtime. GroupIds are never resolved and the groupIds property isn't populated, making this resource a no-op unless you provide the ids directly.

The reference to the appropriate terraform resource is missing.

https://github.com/crossplane-contrib/provider-keycloak/blob/6c28b93c3937aa5bef82f1386068d100974394fe/config/user/config.go#L23

PR is in the making.

**Comment by Breee** [comment]
new release v1.6.0 is building
