### ISSUE TITLE
Feature Request: Add resource types for realm_events

### ISSUE THREAD

**Issue by daniel-palmer-gu** [crossplane-contrib/provider-keycloak#194]
As a Keycloak Administrator, I would like provider-keycloak to support realm_events, so that I can configure realm_events via code

Upstream Terraform: https://registry.terraform.io/providers/mrparkers/keycloak/latest/docs/resources/realm_events

**Comment by Breee** [comment]
i'll get it done asap

**Comment by Breee** [comment]
fyi, i just saw that we already have that.  

`RealmEvents`   in api group  `realm.keycloak.crossplane.io`

**Comment by daniel-palmer-gu** [comment]
Yikes! I missed that. Thanks for the response regardless!
