### ISSUE TITLE
Segmentation fault on provider startup when external secret stores flag is enabled

### ISSUE THREAD

**Issue by Den4200** [crossplane-contrib/provider-keycloak#41]
## Problem
A segmentation fault occurs on startup of this provider when the external secret store flag is enabled.

```
{"level":"info","ts":"2024-02-08T03:40:02Z","logger":"provider-keycloak","msg":"Alpha feature enabled","flag":"EnableAlphaExternalSecretStores"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x19b8b85]

goroutine 1 [running]:
github.com/crossplane-contrib/provider-keycloak/internal/controller/client/protocolmapper.Setup({0x21c4af8, 0xc000580b60}, {{{0x21a9c90, 0xc00033c408}, {0x21a9c60, 0xc0006189d8}, 0x8bb2c97000, 0xa, 0x0, 0x0}, ...})
        github.com/crossplane-contrib/provider-keycloak/internal/controller/client/protocolmapper/zz_controller.go:35 +0x2e5
github.com/crossplane-contrib/provider-keycloak/internal/controller.Setup({0x21c4af8, 0xc000580b60}, {{{0x21a9c90, 0xc00033c408}, {0x21a9c60, 0xc0006189d8}, 0x8bb2c97000, 0xa, 0x0, 0x0}, ...})
        github.com/crossplane-contrib/provider-keycloak/internal/controller/zz_setup.go:49 +0x19d
main.main()
        github.com/crossplane-contrib/provider-keycloak/cmd/provider/main.go:112 +0x1cf2
```

## Cause
Digging into this issue a bit, it seems that the segmentation fault occurs here:
https://github.com/crossplane-contrib/provider-keycloak/blob/6c075c42c056e09a205aded3874ee548d6b1f8a2/internal/controller/client/protocolmapper/zz_controller.go#L35-L36

The cause seems to be that `ESSOptions` is `nil` since it is not set here in the initial setup:
https://github.com/crossplane-contrib/provider-keycloak/blob/6c075c42c056e09a205aded3874ee548d6b1f8a2/cmd/provider/main.go#L93-L110

## Proposal
Looking at the source code for the Azure provider, they have [a few additional lines of code in this section](https://github.com/upbound/provider-azure/blob/80caea55c9a8a0752b8e664cae1e9b92b45ec033/cmd/provider/sql/zz_main.go#L138-L145) to set `ESSOptions`.
```diff
	if *enableExternalSecretStores {
		o.SecretStoreConfigGVK = &v1alpha1.StoreConfigGroupVersionKind
		log.Info("Alpha feature enabled", "flag", features.EnableAlphaExternalSecretStores)

+		o.ESSOptions = &tjcontroller.ESSOptions{}
+		if *essTLSCertsPath != "" {
+			log.Info("ESS TLS certificates path is set. Loading mTLS configuration.")
+			tCfg, err := certificates.LoadMTLSConfig(filepath.Join(*essTLSCertsPath, "ca.crt"), filepath.Join(*essTLSCertsPath, "tls.crt"), filepath.Join(*essTLSCertsPath, "tls.key"), false)
+			kingpin.FatalIfError(err, "Cannot load ESS TLS config.")
+
+			o.ESSOptions.TLSConfig = tCfg
+		}

		// Ensure default store config exists.
		kingpin.FatalIfError(resource.Ignore(kerrors.IsAlreadyExists, mgr.GetClient().Create(context.Background(), &v1alpha1.StoreConfig{
```

I believe adding these few lines of code to the Keycloak Provider will resolve this issue. I would greatly appreciate any help!

**Comment by Breee** [comment]
Hi,
thx for the bugreport. 
v0.7.0 should be available now, please test.  https://marketplace.upbound.io/providers/crossplane-contrib/provider-keycloak/v0.7.0

**Comment by Den4200** [comment]
@Breee I've tested the new release and everything seems to be resolved. Thanks so much for the quick fix! :shipit:
