### ISSUE TITLE
Feature: client scope id ref

### ISSUE THREAD

**Issue by Den4200** [crossplane-contrib/provider-keycloak#48]
## Description
For resources such as `GroupMembershipProtocolMapper` that have a `clientScopeId` field, there are no corresponding `clientScopeIdRef` and `clientScopeIdSelector` fields to reference a `ClientScope`.

This would be something very useful to have!

**Comment by Breee** [comment]
Greetings, 
I added the required changes. 
 
release: https://github.com/crossplane-contrib/provider-keycloak/releases/tag/v0.10.0
new version: https://marketplace.upbound.io/providers/crossplane-contrib/provider-keycloak/v0.10.0
crd: https://marketplace.upbound.io/providers/crossplane-contrib/provider-keycloak/v0.10.0/resources/openidgroup.keycloak.crossplane.io/GroupMembershipProtocolMapper/v1alpha1#doc:spec-forProvider-clientScopeIdRef

Test it please and report back.

**Comment by Den4200** [comment]
Thanks so much @Breee! It works perfectly.
