### ISSUE TITLE
Management Policies

### ISSUE THREAD

**Issue by zonybob** [crossplane-contrib/provider-keycloak#67]
Add support for `managementPolicies`
https://docs.crossplane.io/v1.15/concepts/managed-resources/#managementpolicies

See https://crossplane.slack.com/archives/C01718T2476/p1709044630532719?thread_ts=1709043136.104429&cid=C01718T2476

**Comment by Breee** [comment]
Thx for your contribution,  release  v0.11.0 should be published shortly
