### ISSUE TITLE
ProtocolMapper not applying config section properly

### ISSUE THREAD

**Issue by leunamnauj** [crossplane-contrib/provider-keycloak#90]
Based on the documentation example [**examples/protocol-mappers.yaml**](https://github.com/crossplane-contrib/provider-keycloak/blob/bc754e69afc801016bba442ae68011c9cf933b02/examples/protocol-mappers.yaml)

Since this provider uses [Terraform]( https://registry.terraform.io/providers/mrparkers/keycloak/latest/docs/resources/openid_audience_protocol_mapper) in background I'm trying to also add the following options:

```
"add.to.id.token": "true"
"add.to.access.token": "true"
```

But it seems not to be noticing the changes. I'm wondering if I'm doing something wrong or if it is failing somehow
Thanks!

**Comment by Breee** [comment]
According to the keycloak sourcecode it should be 
- `access.token.claim` and 
- `id.token.claim`  

https://github.com/keycloak/keycloak/blob/cc558b4090eb6707e269d9a581945a6424d0adbc/services/src/main/java/org/keycloak/protocol/oidc/mappers/OIDCAttributeMapperHelper.java#L57

https://github.com/keycloak/keycloak/blob/cc558b4090eb6707e269d9a581945a6424d0adbc/services/src/main/java/org/keycloak/protocol/oidc/mappers/OIDCAttributeMapperHelper.java#L60


Does that work for you? 

If not i'll implement https://registry.terraform.io/providers/Arkaniad/keycloak/latest/docs/resources/openid_audience_protocol_mapper
as ressource

**Comment by leunamnauj** [comment]
Hey @Breee 
It works! 
Much appreciated

**Comment by Breee** [comment]
Great, i'll soon work on some docs that explain everything So people can
also contribute. However, i'm still evaluating on How to restructure the
whole Provider in order to fix all existing issues and issues I faced so
far
