### ISSUE TITLE
LDAP Integration resources are missing

### ISSUE THREAD

**Issue by kaviankarimzadeh** [crossplane-contrib/provider-keycloak#93]
Hi, I would like to know if it's possible to add LDAP integration resources, specifically keycloak_ldap_user_federation and keycloak_ldap_group_mapper, which already exist for Terraform.
And also possibility of assigning keycloak role to LDAP groups.

**Comment by Breee** [comment]
pull request #94  will add this - i'll release most likely tomorrow

**Comment by Breee** [comment]
- Release is out: https://marketplace.upbound.io/providers/crossplane-contrib/provider-keycloak/v0.20.0  
- Can you test and report back? 
- Also: Can you guys do me a favor and create some examples / docs for these resources?   I soon want to provide a big bunch of docs and examples / explanations

**Comment by kaviankarimzadeh** [comment]
Thanks for the fast contribution! Your work is awesome. I’ll review and give feedback ASAP.

**Comment by kaviankarimzadeh** [comment]
I can confirm that it's working properly! Thanks again @Breee

**Comment by Breee** [comment]
Nice, Could you Provide some realworld examples and docs for people that want to use the Ressources? (I don't have LDAP available without setting one up first)

**Comment by kaviankarimzadeh** [comment]
Sure, do you want me to share examples here or add to examples folder in repo?

**Comment by kaviankarimzadeh** [comment]
Here, I've added some examples I used to integrate LDAP with Keycloak for Kubernetes OIDC authentication. I'll include them in the examples here as well.

https://github.com/kaviankarimzadeh/k8s-keycloak-crossplane/tree/main/crossplane
